version: "3.9"

services:
  vue:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8095:8095"
    volumes:
      - .:/warehouse_v6
      - /vue/node_modules
    networks:
      - warehouse-network

networks:
  warehouse-network:
    external: true